name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.5"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Tests
      run: swift test
